build: false
environment:
  matrix:
    - PHP: "C:/PHP"
services:
  - mssql2008r2sp2
  - mssql2012sp1
init:
  - "ECHO %PHP%"
  - "SET PATH=C:\php\;%PATH%"
install:
  - cinst php
test_script:
  - "%PHP%/Scripts/php.exe --version"
