build: false
environment:
  matrix:
    - PHP: "C:/PHP"
services:
  - mssql2008r2sp2
  - mssql2012sp1
init:
  - SET PATH=C:\php\;%PATH%
install:
  - cinst php
  - cd %PHP%
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar self-update
  - php composer install
test_script:
  - "%PHP%/php.exe --version"
