build: false
environment:
  global:
    TESTS_PHINX_DB_ADAPTER_SQLSRV_ENABLED: true
    TESTS_PHINX_DB_ADAPTER_SQLSRV_HOST: SQL2012SP1
    TESTS_PHINX_DB_ADAPTER_SQLSRV_USERNAME: sa
    TESTS_PHINX_DB_ADAPTER_SQLSRV_PASSWORD: Password12!
    TESTS_PHINX_DB_ADAPTER_SQLSRV_DATABASE: master
    TESTS_PHINX_DB_ADAPTER_SQLSRV_PORT: 1433
  matrix:
    - PHP: "C:/PHP"
services:
  - mssql2008r2sp2
  - mssql2012sp1
init:
  - SET PATH=C:\php\;%PATH%
install:
  - cinst php
  - cd C:\PHP
  - copy php.ini-production php.ini
  - echo "extension_dir=ext" >> php.ini
  - echo "extension=php_openssl.dll" >> php.ini
  - cd C:\projects\phinx
  - php -c c:/PHP/php.ini -r "readfile('https://getcomposer.org/installer');" | php
  - php -c c:/PHP/php.ini composer.phar self-update
  - php -c c:/PHP/php.ini composer install
  - php -c c:/PHP/php.ini vendor/bin/phpunit
test_script:
  - "%PHP%/php.exe --version"
